config/routes.rb
Rails.application.routes.draw do
  
  resources :rooms
  captcha_route
  get 'static_pages/home'
  get 'static_pages/team'

  devise_for :users
  resources :flies
  resources :crosses
  resources :stocks

  get 'crosses/:id/history' => 'crosses#history'
  get ':id/history' => 'crosses#history'
  get ':id/qr' => 'crosses#qr'
  get '/crosses/:id/qr' => 'crosses#qr'
  get ':id' => 'crosses#show', :as => 'short'
  get ':id/chr' => 'crosses#chromosome'
  get ':id/pnt' => 'crosses#punnett'

  get '/stocks/n/:fly_to_stock' => 'stocks#create'
  get '/stocks/x/add' => 'stocks#add'

  get 'copy/:id' => 'crosses#copy', :as => 'copy'

  root :to => "static_pages#home"

  mathjax 'mathjax'

end

app/models/stock.rb
class Stock < ActiveRecord::Base

  belongs_to :user

  default_scope { order('number ASC') }
end

app/controllers/stocks_controller.rb
class StocksController < ApplicationController
  before_action :set_stock, only: [:show, :edit, :update, :destroy]
  before_action :correct_user, only: [:edit,:update,:destroy,:show]
  before_action :logged_user, only: [:index, :new, :create, :show, :newstock]

  # GET /stocks
  # GET /stocks.json
  def index
    @stocks = Stock.where("user_id = ?", current_user.id)
    respond_to do |format|
      format.html
      format.csv do
        headers['Content-Disposition'] = "attachment; filename=\"stock-list.tsv\""
        headers['Content-Type'] ||= 'text/csv'
      end
    end
  end

  # GET /stocks/1
  # GET /stocks/1.json
  def show
    if @stock.room_id != nil
      @room = Room.find(@stock.room_id)
    end
  end

  # GET /stocks/new
  def new
    @stock = Stock.new
  end

  # GET /stocks/1/edit
  def edit
  end

  def newstock
  end

  def add
    chr_X = homozygous_tester(cross_params[:X])
    chr_II = homozygous_tester(cross_params[:II])
    chr_III = homozygous_tester(cross_params[:III])
    chr_IV = homozygous_tester(cross_params[:IV])

    @fly = Fly.new(:chr1 => chr_X, :chr2 => chr_II, :chr3 => chr_III, :chr4 => chr_IV, :cross_id => 0)
    @fly.save
    @stock = Stock.new(:number => cross_params[:number], :name => "", :fly_id => @fly.id, :lab_id => "",
                       :user_id => current_user.id, :comment => "", :date_established => "",
                       :room_id => cross_params[:room_id], :reference => "", :received_from => "")
    respond_to do |format|
      if @stock.save
        format.html { redirect_to @stock, notice: 'Stock was successfully created.' }
      end
    end
  end

  # POST /stocks
  # POST /stocks.json
  def create
    @fly = Fly.find(params[:fly_to_stock])

    @stock = Stock.new(:number => 0, :name => "", :fly_id => @fly.id, :lab_id => "",
                       :user_id => current_user.id, :comment => "", :date_established => "",
                       :room_id => "", :reference => "", :received_from => "")

    respond_to do |format|
      if @stock.save
        format.html { redirect_to stocks_path, notice: 'Stock was successfully created.' }
        format.json { render :show, status: :created, location: @stock }
      else
        format.html { redirect_to root_path }
        format.json { render json: @stock.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /stocks/1
  # PATCH/PUT /stocks/1.json
  def update
    respond_to do |format|
      if @stock.update(stock_params)
        format.html { redirect_to @stock, notice: 'Stock was successfully updated.' }
        format.json { render :show, status: :ok, location: @stock }
      else
        format.html { render :edit }
        format.json { render json: @stock.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /stocks/1
  # DELETE /stocks/1.json
  def destroy
    @stock.destroy
    respond_to do |format|
      format.html { redirect_to stocks_url, notice: 'Stock was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_stock
    @stock = Stock.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def stock_params
    params.require(:stock).permit(:number, :name, :fly_id, :lab_id, :user_id, :comment, :date_established, :room_id, :reference, :received_from, :lethal, :balancers)
  end
  def cross_params
    params.require(:cross).permit(:description,:m_X,:m_II,:m_III,:m_IV,:f_X,:f_II,:f_III,:f_IV,:lethal,:balancers,
                                  :parent,:male_id,:female_id,:link,
                                  :X,:II,:III,:IV,:crossdate,:number,:room_id)
  end
  def homozygous_tester(chromosome)
    if !chromosome.include? "/"
      return chromosome + "/" + chromosome
    else
      return chromosome
    end
  end
  def correct_user
    if user_signed_in?
      if current_user.id != @stock.user_id
        redirect_to root_url
      end
    else
      redirect_to root_url
    end
  end
  def logged_user
    if user_signed_in?

    else
      redirect_to root_url, notice: 'You need to be logged in.'
    end
  end
end

app/helpers/stocks_helper.rb
module StocksHelper
end

app/views/stocks/_form.html.erb
<%= form_for(@stock, auto_labels: false) do |f| %>
  <% if @stock.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@stock.errors.count, "error") %> prohibited this stock from being saved:</h2>
      <ul>
        <% @stock.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= f.label "Stock number" %><br>
    <%= f.number_field :number %>
  </div>
  <div class="field">
    <%= f.label :room_id %><br>
    <%= f.collection_select :room_id, Room.where("user_id = ?", current_user.id), :id, :name, :prompt => "Choose Stock Room" %>
  </div>
  <div class="field">
    <%= f.label :comment %><br>
    <%= f.text_area :comment %>
  </div>
  <div class="field">
    <%= f.label :date_established %><br>
    <%= f.date_select :date_established %>
  </div>
  <div class="field">
    <%= f.label :reference %><br>
    <%= f.text_area :reference %>
  </div>
  <div class="field">
    <%= f.label :received_from %><br>
    <%= f.text_area :received_from %>
  </div>
  <%= f.hidden_field :user_id %>
  <%= f.hidden_field :lab_id %>
  <%= f.hidden_field :fly_id %>
  <%= f.hidden_field :name %>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/stocks/edit.html.erb
<div class="white-bg">
<nav aria-label="You are here:" role="navigation">
  <ul class="breadcrumbs">
    <li><a href="<%= request.base_url %>">Drosophila.me</a></li>
    <li><a href="<%= request.base_url %>/stocks">Stocks</a></li>
    <li>
      <span class="show-for-sr">Current: </span> Edit stock
          </li>
  </ul>
</nav>
<h1>Editing Stock</h1>
<div class="panel">
  <%= render 'form' %>
</div>
</div>

app/views/stocks/index.csv.erb
<%- headers = ['Room','Stock number','X chromosome','II chromosome','III chromosome','IV chromosome','Comment','Reference','Received from','Date established'] -%>
<%= CSV.generate_line(headers, col_sep: "\t") %>
<%- @stocks.each do |stock| -%>
<%
	if stock.comment == "" 
		stock.comment = nil 
	end
	if stock.reference == "" 
		stock.reference = nil 
	end
	if stock.received_from == "" 
		stock.received_from = nil 
	end
%>
<%
	fly = Fly.find(stock.fly_id)
	if stock.room_id != nil
		room = Room.find(stock.room_id).name
	else
		room = nil
	end
%>
<%= CSV.generate_line([room,stock.number,fly.chr1,fly.chr2,fly.chr3,fly.chr4,stock.comment,stock.reference,stock.received_from,stock.date_established], col_sep: "\t" ) -%>
<%- end -%>

app/views/stocks/index.html.erb
<div class="white-bg">
<nav aria-label="You are here:" role="navigation">
  <ul class="breadcrumbs">
    <li><a href="<%= request.base_url %>">Drosophila.me</a></li>
    <li>
      <span class="show-for-sr">Current: </span> Stocks
          </li>
  </ul>
</nav>
<h1>Your fly stocks</h1>
<a href="<%= new_stock_path %>" class="button small secondary">New Stock</a>
<a href="<%= rooms_path %>" class="button small secondary">Stock rooms</a>
<a href="<%= stocks_path(format: :csv) %>" class="button small secondary">Download stocks</a>
<%= form_for :cross, :url => {:controller => "crosses", :action => "create"}, :method => "post", auto_labels: false do |f| %>
<div class="row">
  <div class="large-8 column">
  <table>
    <thead>
      <tr>
        <th>Stock
        <br />
          Room</th>
        <th>Stock
        <br />
          Number</th>
        <th>Genotype</th>
        <th>Cross</th>
      </tr>
    </thead>
    <tbody>
      <% @stocks.each do |stock| %>
        <tr>
          <td>
            <% if stock.room_id != nil %>
              <% room = Room.find(stock.room_id) %>
              <%= room.name %>
            <% end %>
          </td>
          <td>
            <a href="stocks/<%= stock.id %>">
              <%= stock.number %>
            </a>
          </td>
          <td>
            <a href="stocks/<%= stock.id %>" class="button secondary tiny hollow">
              <% fly = Fly.find(stock.fly_id) %>
              <% chromosomes = [fly.chr1.split('/').to_set, fly.chr2.split('/').to_set, fly.chr3.split('/').to_set, fly.chr4.split('/').to_set] %>
              \[
              <% semikolon = 0 %>
              <% chromosomes.each do |chr| %>
                <% if chr.size > 1 %>
                  <% if semikolon != 0 %>;<% end %>
                  <% chr %>
                  \dfrac
                    <% chr.each do |n| %>
                    {<%= n %>}
                    <% end %>
                <% else %>
                  <% if semikolon != 0 %>;<% end %>
                  <% chr.each do |n| %>
                    <%= n %>
                  <% end %>
                <% end %>
                <% semikolon = 1 %>
              <% end %>
              \]

            </a>
          </td>
          <td>
            &#9794; 
            <%= f.radio_button(:male_id, fly.id, label: false) %>
            <br />
            &#9792; 
            <%= f.radio_button(:female_id, fly.id, label: false) %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>
  <div class="large-4 column">
    <div class="row panel callout secondary">
      <h5>Add new fly to cross</h5>
      <div class="large-12 columns">
        &#9794; 
            <%= f.radio_button(:male_id, "new", label: false) %>
        | &#9792; 
            <%= f.radio_button(:female_id, "new", label: false) %>
      </div>
      <div class="large-6 columns">
        <label>X chromosome
          <%= f.text_field :X, :value => "+/+" %>
        </label>
      </div>
      <div class="large-6 columns">
        <label>Chromosome 2
          <%= f.text_field :II, :value => "+/+" %>
        </label>
      </div>
      <div class="large-6 columns">
        <label>Chromosome 3
          <%= f.text_field :III, :value => "+/+" %>
        </label>
      </div>
      <div class="large-6 columns">
        <label>Chromosome 4
          <%= f.text_field :IV, :value => "+/+" %>
        </label>
      </div>
    </div>
    <div class="panel">
      <h5>Lethal alleles</h5>
      <label>Alleles separated by semicolon [;] <%= f.text_field :lethal %></label>
      <h5>Balancers</h5>
      <label>Balancers separated by semicolon [;] <%= f.text_field :balancers %></label>
      <h5>Comments</h5>
      <label>Describe this cross <%= f.text_field :description %></label>
    </div>
    <div class="panel">
      <h5>Date of cross</h5>
      <%= f.date_select :crossdate %>
    </div>
    <%= f.hidden_field(:parent, :value => "stock") %>
  <%= f.submit 'Cross', class: 'button success' %>
  </div>
</div>
<% end %>
</div>

app/views/stocks/new.html.erb
<div class="white-bg">
<nav aria-label="You are here:" role="navigation">
  <ul class="breadcrumbs">
    <li><a href="<%= request.base_url %>">Drosophila.me</a></li>
    <li><a href="<%= request.base_url %>/stocks">Stocks</a></li>
    <li>
      <span class="show-for-sr">Current: </span> New stock
          </li>
  </ul>
</nav>
<h1>Add new stock</h1>
<%= form_for :cross, :url => {:controller => "stocks", :action => "add"}, :method => "get", auto_labels: false do |f| %>
  <div class="field">
    <div class="panel">
      <h5>Genotype</h5>
      <h6>Separate sister chromosomes with a slash [/] and alleles on the same chromosome with a comma [,]</h6>
      <div class="row">
        <div class="large-6 columns">
          <label>X chromosome
          <%= f.text_field :X, :value => "+/+" %>
          </label>
        </div>
        <div class="large-6 columns">
          <label>Chromosome 2
          <%= f.text_field :II, :value => "+/+" %>
          </label>
        </div>
        <div class="large-6 columns">
          <label>Chromosome 3
          <%= f.text_field :III, :value => "+/+" %>
          </label>
        </div>
        <div class="large-6 columns">
          <label>Chromosome 4
          <%= f.text_field :IV, :value => "+/+" %>
          </label>
        </div>
      </div>
    </div>
    <div class="panel">
      <h5>Lethal alleles</h5>
      <label>Alleles separated by semicolon [;] <%= f.text_field :lethal %></label>
      <h5>Balancers</h5>
      <label>Balancers separated by semicolon [;] <%= f.text_field :balancers %></label>
    </div>
    <div class="panel">
    <div class="field panel">
      <%= f.label :room_id %><br>
      <%= f.collection_select :room_id, Room.where("user_id = ?", current_user.id), :id, :name, :prompt => "Choose Stock Room" %>
    </div>
    <div class="field panel">
      <%= f.label "Stock number" %><br>
      <%= f.number_field :number %>
    </div>
    <div class="actions">
      <%= f.submit %>
    </div>
  </div>
<% end %>
</div>

app/views/stocks/show.html.erb
<div class="white-bg">
<nav aria-label="You are here:" role="navigation">
  <ul class="breadcrumbs">
    <li><a href="<%= request.base_url %>">Drosophila.me</a></li>
    <li><a href="<%= request.base_url %>/stocks">Stocks</a></li>
    <li>
      <span class="show-for-sr">Current: </span> Show stock
          </li>
  </ul>
</nav>
<h1>Stock n. <%= @stock.number %></h1>
<a href="<%= new_stock_path %>" class="button small secondary">New Stock</a>
<div class="panel">
  <p>
    <strong>Genotype:</strong>
    <% fly = Fly.find(@stock.fly_id) %>
    <%= fly.chr1 %> ; <%= fly.chr2 %> ; <%= fly.chr3 %> ; <%= fly.chr4 %>
  </p>
  <p>
    <strong>Stock room:</strong>
    <% if @room != nil %>
      <%= @room.name %>
    <% end %>
  </p>
  <p>
    <strong>Comment:</strong>
    <%= @stock.comment %>
  </p>
  <p>
    <strong>Date established:</strong>
    <% if @stock.date_established != nil %>
      <%= @stock.date_established.strftime("%B %d, %Y") %>
    <% end %>
  </p>
  <p>
    <strong>Reference:</strong>
    <%= @stock.reference %>
  </p>
  <p>
    <strong>Received from:</strong>
    <%= @stock.received_from %>
  </p>
  <a href="<%= @stock.id %>/edit" class="button small secondary"><i class="fi-page-edit" ></i> Edit</a>
  <%= link_to @stock, method: :delete, data: { confirm: "Are you sure?" }, class: "button small alert" do %>
    <i class="fi-trash" ></i> Delete stock
  <% end %>
</div>
</div>