config/routes.rb
Rails.application.routes.draw do
  
  resources :rooms
  captcha_route
  get 'static_pages/home'
  get 'static_pages/team'

  devise_for :users
  resources :flies
  resources :crosses
  resources :stocks

  get 'crosses/:id/history' => 'crosses#history'
  get ':id/history' => 'crosses#history'
  get ':id/qr' => 'crosses#qr'
  get '/crosses/:id/qr' => 'crosses#qr'
  get ':id' => 'crosses#show', :as => 'short'
  get ':id/chr' => 'crosses#chromosome'
  get ':id/pnt' => 'crosses#punnett'

  get '/stocks/n/:fly_to_stock' => 'stocks#create'
  get '/stocks/x/add' => 'stocks#add'

  get 'copy/:id' => 'crosses#copy', :as => 'copy'

  root :to => "static_pages#home"

  mathjax 'mathjax'

end

app/models/room.rb
class Room < ActiveRecord::Base
  belongs_to :user
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_action :set_room, only: [:show, :edit, :update, :destroy]
  before_action :correct_user, only: [:edit,:update,:destroy]
  before_action :logged_user, only: [:index, :new, :create, :copy]

  # GET /rooms
  # GET /rooms.json
  def index
    @rooms = Room.where("user_id = ?", current_user.id)
  end

  # GET /rooms/1
  # GET /rooms/1.json
  def show
  end

  # GET /rooms/new
  def new
    @room = Room.new
  end

  # GET /rooms/1/edit
  def edit
  end

  # POST /rooms
  # POST /rooms.json
  def create
    @room = Room.new(room_params)
    @room = Room.new(:name => room_params[:name], :temperature => room_params[:temperature], :user_id => current_user.id)

    respond_to do |format|
      if @room.save
        format.html { redirect_to rooms_path, notice: 'Room was successfully created.' }
        format.json { render :show, status: :created, location: @room }
      else
        format.html { render :new }
        format.json { render json: @room.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /rooms/1
  # PATCH/PUT /rooms/1.json
  def update
    respond_to do |format|
      if @room.update(room_params)
        format.html { redirect_to rooms_path, notice: 'Room was successfully updated.' }
        format.json { render :show, status: :ok, location: @room }
      else
        format.html { render :edit }
        format.json { render json: @room.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /rooms/1
  # DELETE /rooms/1.json
  def destroy
    @room.destroy
    respond_to do |format|
      format.html { redirect_to rooms_url, notice: 'Room was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_room
    @room = Room.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def room_params
    params.require(:room).permit(:name, :temperature)
  end

  def correct_user
    if user_signed_in?
      if current_user.id != @room.user_id
        redirect_to root_url
      end
    else
      redirect_to root_url
    end
  end
  def logged_user
    if user_signed_in?

    else
      redirect_to root_url, notice: 'You need to be logged in.'
    end
  end

end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/views/rooms/_form.html.erb
<%= form_for(@room, auto_labels: false) do |f| %>
  <% if @room.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@room.errors.count, "error") %> prohibited this room from being saved:</h2>
      <ul>
        <% @room.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :temperature %><br>
    <%= f.text_field :temperature %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/rooms/edit.html.erb
<div class="white-bg">
<nav aria-label="You are here:" role="navigation">
  <ul class="breadcrumbs">
    <li><a href="<%= request.base_url %>">Drosophila.me</a></li>
    <li><a href="<%= request.base_url %>/stocks">Stocks</a></li>
    <li>
      <span class="show-for-sr">Current: </span> Edit room
          </li>
  </ul>
</nav>
<h1>Editing Room</h1>
<%= render 'form' %>
</div>

app/views/rooms/index.html.erb
<div class="white-bg">
<nav aria-label="You are here:" role="navigation">
  <ul class="breadcrumbs">
    <li><a href="<%= request.base_url %>">Drosophila.me</a></li>
    <li><a href="<%= request.base_url %>/stocks">Stocks</a></li>
    <li>
      <span class="show-for-sr">Current: </span> Room list
          </li>
  </ul>
</nav>
<h1>Your stock rooms</h1>
<a href="<%= new_room_path %>" class="button small secondary">New Stock Room</a>
<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Temperature</th>
      <th colspan="2"></th>
    </tr>
  </thead>
  <tbody>
    <% @rooms.each do |room| %>
      <tr>
        <td><%= room.name %></td>
        <td><%= room.temperature %></td>
        <td><%= link_to 'Edit', edit_room_path(room) %></td>
        <td><%= link_to 'Delete', room, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>

app/views/rooms/new.html.erb
<div class="white-bg">
<nav aria-label="You are here:" role="navigation">
  <ul class="breadcrumbs">
    <li><a href="<%= request.base_url %>">Drosophila.me</a></li>
    <li><a href="<%= request.base_url %>/stocks">Stocks</a></li>
    <li>
      <span class="show-for-sr">Current: </span> New room
          </li>
  </ul>
</nav>
<h1>New Room</h1>
<%= render 'form' %>
</div>