config/routes.rb
Rails.application.routes.draw do
  
  resources :rooms
  captcha_route
  get 'static_pages/home'
  get 'static_pages/team'

  devise_for :users
  resources :flies
  resources :crosses
  resources :stocks

  get 'crosses/:id/history' => 'crosses#history'
  get ':id/history' => 'crosses#history'
  get ':id/qr' => 'crosses#qr'
  get '/crosses/:id/qr' => 'crosses#qr'
  get ':id' => 'crosses#show', :as => 'short'
  get ':id/chr' => 'crosses#chromosome'
  get ':id/pnt' => 'crosses#punnett'

  get '/stocks/n/:fly_to_stock' => 'stocks#create'
  get '/stocks/x/add' => 'stocks#add'

  get 'copy/:id' => 'crosses#copy', :as => 'copy'

  root :to => "static_pages#home"

  mathjax 'mathjax'

end

app/controllers/crosses_controller.rb
class CrossesController < ApplicationController
  before_action :set_cross, only: [:show, :edit, :update, :destroy, :history, :copy, :qr, :chromosome, :punnett]
  before_action :correct_user, only: [:edit,:update,:destroy]
  before_action :logged_user, only: [:index, :new, :create, :copy]

  # GET /crosses
  # GET /crosses.json
  def index
    @crosses = Cross.where("user_id = ?", current_user.id)
  end

  def copy
    require 'securerandom'
    link = SecureRandom.hex

    @flym = Fly.find(@cross.male_id)
    @flyf = Fly.find(@cross.female_id)

    @c_flym = Fly.new(:chr1 => @flym.chr1, :chr2 => @flym.chr2, :chr3 => @flym.chr3, :chr4 => @flym.chr4)
    @c_flym.save

    @c_flyf = Fly.new(:chr1 => @flyf.chr1, :chr2 => @flyf.chr2, :chr3 => @flyf.chr3, :chr4 => @flyf.chr4)
    @c_flyf.save

    @c_cross = Cross.new(:male_id => @c_flym.id, :link => link,
                         :female_id => @c_flyf.id, :lethal => @cross.lethal,
                         :balancers => @cross.balancers, :description => @cross.description,
                         :parent => @cross.parent, :user_id => current_user.id, :crossdate => @cross.crossdate)

    flies = Fly.where("cross_id = ? AND id != ? AND id != ?", @cross.id, @cross.male_id, @cross.female_id)

    respond_to do |format|
      if @c_cross.save
        @c_flym.update(:cross_id => @c_cross.id)
        @c_flyf.update(:cross_id => @c_cross.id)
        flies.each do |f|
          @fly = Fly.new(:chr1 => f.chr1, :chr2 => f.chr2, :chr3 => f.chr3, :chr4 => f.chr4, :cross_id => @c_cross.id)
          @fly.save
        end
        format.html { redirect_to short_path(@c_cross.friendly_id), notice: 'Cross was copied to your collection' }
      else
        format.html { render @cross, notice: 'Cross could not be copied.' }
      end
    end

  end

  def history
    @crosses = []
    @crosses.append(Cross.find(@cross.id))
    ncross = Cross.find(@cross.id)

    run = true

    while run;
      if ncross.parent.to_i == 0
        break
      end

      ncross = Cross.find(ncross.parent)
      @crosses.append(ncross)

    end

    @crosses.reverse!
  end

  # GET /crosses/1
  # GET /crosses/1.json
  def show
    require 'securerandom'
    @random_string = SecureRandom.hex

    flym = Fly.find(@cross.male_id)
    flyf = Fly.find(@cross.female_id)

    @parent_male = [flym.chr1.split('/').to_set, flym.chr2.split('/').to_set, flym.chr3.split('/').to_set, flym.chr4.split('/').to_set]
    @parent_female = [flyf.chr1.split('/').to_set, flyf.chr2.split('/').to_set, flyf.chr3.split('/').to_set, flyf.chr4.split('/').to_set]

    prog = Fly.where("cross_id = ? AND id != ? AND id != ?", @cross.id, @cross.male_id, @cross.female_id)

    @progeny = []
    @prog_id = []
    @x_chr = []
    @II_chr = []
    @III_chr = []
    @IV_chr = []
    prog.each do |n|
      @progeny.append([n.chr1.split('/').to_set, n.chr2.split('/').to_set, n.chr3.split('/').to_set, n.chr4.split('/').to_set])
      @prog_id.append(n.id)
      @x_chr.append([n.chr1.split('/').to_set])
      @II_chr.append([n.chr2.split('/').to_set])
      @III_chr.append([n.chr3.split('/').to_set])
      @IV_chr.append([n.chr4.split('/').to_set])
    end

    @x_chr = @x_chr.uniq
    @II_chr = @II_chr.uniq
    @III_chr = @III_chr.uniq
    @IV_chr = @IV_chr.uniq

    @balancers = @cross.balancers.split(';')
    @balancer_string = @cross.balancers
    @lethal = @cross.lethal.split(';')
    @lethal_string = @cross.lethal

    @current_url = request.original_url

  end

  def chromosome
    require 'securerandom'
    @random_string = SecureRandom.hex

    flym = Fly.find(@cross.male_id)
    flyf = Fly.find(@cross.female_id)

    @parent_male = [flym.chr1.split('/').to_set, flym.chr2.split('/').to_set, flym.chr3.split('/').to_set, flym.chr4.split('/').to_set]
    @parent_female = [flyf.chr1.split('/').to_set, flyf.chr2.split('/').to_set, flyf.chr3.split('/').to_set, flyf.chr4.split('/').to_set]

    prog = Fly.where("cross_id = ? AND id != ? AND id != ?", @cross.id, @cross.male_id, @cross.female_id)

    @progeny = []
    @prog_id = []
    @x_chr = []
    @II_chr = []
    @III_chr = []
    @IV_chr = []
    prog.each do |n|
      @progeny.append([n.chr1.split('/').to_set, n.chr2.split('/').to_set, n.chr3.split('/').to_set, n.chr4.split('/').to_set])
      @prog_id.append(n.id)
      @x_chr.append([n.chr1.split('/').to_set])
      @II_chr.append([n.chr2.split('/').to_set])
      @III_chr.append([n.chr3.split('/').to_set])
      @IV_chr.append([n.chr4.split('/').to_set])
    end

    @x_chr = @x_chr.uniq
    @II_chr = @II_chr.uniq
    @III_chr = @III_chr.uniq
    @IV_chr = @IV_chr.uniq

    @balancers = @cross.balancers.split(';')
    @balancer_string = @cross.balancers
    @lethal = @cross.lethal.split(';')
    @lethal_string = @cross.lethal

    @current_url = request.original_url
  end

  def punnett

    @balancers = @cross.balancers.split(';')
    @balancer_string = @cross.balancers
    @lethal = @cross.lethal.split(';')
    @lethal_string = @cross.lethal

    flym = Fly.find(@cross.male_id)
    flyf = Fly.find(@cross.female_id)

    chr1_m = flym.chr1.split('/')
    if depth(chr1_m) == 0
      chr1_m = [flym.chr1,flym.chr1]
    end
    chr2_m = flym.chr2.split('/')
    if depth(chr2_m) == 0
      chr2_m = [flym.chr2,flym.chr2]
    end
    chr3_m = flym.chr3.split('/')
    if depth(chr3_m) == 0
      chr3_m = [flym.chr3,flym.chr3]
    end
    chr4_m = flym.chr4.split('/')
    if depth(chr4_m) == 0
      chr4_m = [flym.chr4,flym.chr4]
    end
    chr1_f = flyf.chr1.split('/')
    if depth(chr1_f) == 0
      chr1_f = [flyf.chr1,flyf.chr1]
    end
    chr2_f = flyf.chr2.split('/')
    if depth(chr2_f) == 0
      chr2_f = [flyf.chr2,flyf.chr2]
    end
    chr3_f = flyf.chr3.split('/')
    if depth(chr3_f) == 0
      chr3_f = [flyf.chr3,flyf.chr3]
    end
    chr4_f = flyf.chr4.split('/')
    if depth(chr4_f) == 0
      chr4_f = [flyf.chr4,flyf.chr4]
    end

    @par_male = [chr1_m,chr2_m,chr3_m,chr4_m]
    @par_female = [chr1_f,chr2_f,chr3_f,chr4_f]

    @parent_male = [flym.chr1.split('/').to_set, flym.chr2.split('/').to_set, flym.chr3.split('/').to_set, flym.chr4.split('/').to_set]
    @parent_female = [flyf.chr1.split('/').to_set, flyf.chr2.split('/').to_set, flyf.chr3.split('/').to_set, flyf.chr4.split('/').to_set]
    @current_url = request.original_url

    @p_mal = [0,0,0,0]
    @p_femal = [0,0,0,0]

    if chr1_m[0] == "+" and chr1_m[1] == "-" and chr1_f[0] == "+" and chr1_f[1] == "+"
      chr1_m[1] = "+"
    end
    if chr1_m[1] == "+" and chr1_m[0] == "-" and chr1_f[0] == "+" and chr1_f[1] == "+"
      chr1_m[0] = "+"
    end

    chr_n = 0
    @par_male.each do |m|
      if m[0] != "+" or m[1] != "+"
        @p_mal[chr_n] = m
      end
      chr_n = chr_n + 1
    end

    chr_n = 0
    @par_female.each do |f|
      if f[0] != "+" or f[1] != "+"
        @p_femal[chr_n] = f.to_a
      end
      chr_n = chr_n + 1
    end

    i = 0
    while i < 3 do
        if @p_mal[i] == 0 and @p_femal[i] != 0
          @p_mal[i] = ["+","+"]
        end
        if @p_mal[i] != 0 and @p_femal[i] == 0
          @p_femal[i] = ["+","+"]
        end
        i = i + 1
      end

      @p_mal = @p_mal - [0]
      @p_femal = @p_femal - [0]

      @male_chrs = @p_mal[0]
      @female_chrs = @p_femal[0]

      notfirst = false
      @p_mal.each do |p|
        if notfirst
          @male_chrs = @male_chrs.product(p)
        end
        notfirst = true
      end
      notfirst = false
      @p_femal.each do |p|
        if notfirst
          @female_chrs = @female_chrs.product(p)
        end
        notfirst = true
      end

      if @p_mal.size == 0
        @male_chrs = [["+"]]
        @female_chrs = [["+"]]
      end

      @male_chrs = @male_chrs.uniq
      @female_chrs = @female_chrs.uniq

    end

    def qr
      qr_img = RQRCode::QRCode.new("http://drosophila.me/" + @cross.friendly_id.to_s )
      qr_img = qr_img.to_img.resize(500,500)
      qr_fly = MiniMagick::Image.read(qr_img.to_blob)
      fly_img = MiniMagick::Image.open("app/assets/images/small.png")

      qr_result = qr_fly.composite(fly_img) do |c|
        c.compose "Over"    # OverCompositeOp
        c.geometry "+0+0" # copy second_image onto first_image from (20, 20)
      end

      @qr_code = qr_result.to_blob
    end

    # GET /crosses/new
    def new
      @cross = Cross.new
    end

    # GET /crosses/1/edit
    def edit
    end

    # POST /crosses
    # POST /crosses.json
    def create

      if cross_params[:parent].to_i >= 1

        @old_cross = Cross.find(cross_params[:parent])

        if cross_params[:male_id] == nil
          redirect_to @old_cross, notice: 'Not all parents were selected.'
          interrup = 1
        elsif cross_params[:female_id] == nil
          redirect_to @old_cross, notice: 'Not all parents were selected.'
          interrup = 1
        elsif cross_params[:male_id] == "male_chr_s"
          if params[:m_X] == nil or params[:m_II] == nil or params[:m_III] == nil or params[:m_IV] == nil
            redirect_to @old_cross, notice: 'Not all chromosomes were selected.'
            interrup = 1
          end
        elsif cross_params[:female_id] == "female_chr_s"
          if params[:f_X] == nil or params[:f_II] == nil or params[:f_III] == nil or params[:f_IV] == nil
            redirect_to @old_cross, notice: 'Not all chromosomes were selected.'
            interrup = 1
          end
        end
      end

      if cross_params[:parent] == "stock"
        if cross_params[:male_id] == nil
          redirect_to stocks_path, notice: 'Not all parents were selected.'
          interrup = 1
        elsif cross_params[:female_id] == nil
          redirect_to stocks_path, notice: 'Not all parents were selected.'
          interrup = 1
        end
      end

      date = Date.new cross_params["crossdate(1i)"].to_i, cross_params["crossdate(2i)"].to_i, cross_params["crossdate(3i)"].to_i

      if interrup != 1
        require 'securerandom'

app/helpers/crosses_helper.rb
module CrossesHelper
	def chromosomeMath(input)
		out = "\\["
		input.each do |chr|
			if chr.size > 1 
				out = out + "\\dfrac"
				chr.each do |n|
					out = out + " {" + n + "}"
				end
			else
				chr.each do |n|
					out = out + n
				end
			end
		end
		out = out + "\\]"
		return out
	end

	def cleanChromosome(input)
		out = ""
		input.each do |chr|
			if chr.size > 1 
				counter = 0
				chr.each do |n|
					out = out + n
					if counter == 0
						out = out + "/"
					end
					counter = 1
				end
			else
				chr.each do |n|
					out = out + n
				end
			end
		end
		return out
	end

	def checkLetality(input,balancers,lethal)
		death = false
		input.each do |chr|
			if chr.size > 1
				up = chr.to_a[0].split(',')
				down = chr.to_a[1].split(',')

				up.each do |u|
					down.each do |d|
						if u == d
							balancers.each do |b|
								if u == b
									death = true
								end
							end
							lethal.each do |l|
								if u == l
									death = true
								end
							end
						end
					end
				end
			else
				n = chr.to_a
				balancers.each do |b|
						if n[0] == b
							death = true
						end
				end
				lethal.each do |b|
						if n[0] == b
							death = true
						end
				end
			end
		end

		return death

	end

end

app/views/crosses/chromosome.html.erb
<div class="white-bg">
<nav aria-label="You are here:" role="navigation">
  <ul class="breadcrumbs">
    <li><a href="<%= request.base_url %>">Drosophila.me</a></li>
    <li><a href="<%= request.base_url %>/crosses">Crosses</a></li>
    <li>
      <span class="show-for-sr">Current: </span> Chromosome view
          </li>
  </ul>
</nav>
<h1>Show cross</h1>
<% g_user = User.find(@cross.user_id) %>
<div class="row">
  <div class="large-2 column">
    <a href="mailto:<%= g_user.email %>" alt="<%= g_user.email %>" title="<%= g_user.email %>">
      <%= image_tag g_user.gravatar_url, :class=> "img-circular" %>
    </a>
  </div>
  <div class="large-5 column">
    <% if @cross.parent.to_i >= 1 %>
      <a href="<%= short_path %>/history"><i class="fi-page-multiple"></i> Cross history</a>
      <br />
    <% end %>
    <a href="<%= short_path %>/qr"><i class="fi-camera"></i> QR code</a>
    <br />
    <% if user_signed_in?
if g_user.id == current_user.id %>
      <%= link_to @cross, method: :delete, data: { confirm: "Are you sure? The cross and all it's derivatives would be deleted." } do %>
        <i class="fi-trash" ></i> Delete cross
      <% end %>
    <% else %>
      <%= link_to copy_path do %>
        <i class="fi-page-copy" ></i> Copy cross
      <% end %>
    <% end %>
  <% end %>
</div>
<div class="large-5 column">
  <p><%= @cross.crossdate.strftime("Crossed on %B %d, %Y") %><br />
    <%= @cross.description %></p>
</div>
</div>
<br />
<p>
  <a href="<%= short_path %>" class="button small secondary">Fly view</a>
  <a href="<%= short_path %>/chr" class="button small primary">Chromosome view</a>
  <a href="<%= short_path %>/pnt" class="button small secondary">Punnett square</a>
</p>
<%= form_for :cross, :url => {:action => "create"}, :method => "post", auto_labels: false do |f| %>
  <div class="row">
    <div class="large-8 column">
      \(\underbrace{

&#x2642; \quad 

    <% semikolon = 0 %>
      <% @parent_male.each do |chr| %>
        <% if chr.size > 1 %>
          <% if semikolon != 0 %>;<% end %>
          <% chr %>
          \dfrac
            <% chr.each do |n| %>
            {<%= n %>}
            <% end %>
        <% else %>
          <% if semikolon != 0 %>;<% end %>
          <% chr.each do |n| %>
            <%= n %>
          <% end %>
        <% end %>
        <% semikolon = 1 %>
      <% end %>
      \qquad X \qquad 

    <% semikolon = 0 %>
      <% @parent_female.each do |chr| %>
        <% if chr.size > 1 %>
          <% if semikolon != 0 %>;<% end %>
          <% chr %>
          \dfrac
            <% chr.each do |n| %>
            {<%= n %>}
            <% end %>
        <% else %>
          <% if semikolon != 0 %>;<% end %>
          <% chr.each do |n| %>
            <%= n %>
          <% end %>
        <% end %>
        <% semikolon = 1 %>
      <% end %>
      \quad &#x2640;
}\)

    <% 
if user_signed_in?
if g_user.id == current_user.id %>
        <% n_chr = []
        @x_chr.each do |input|
            input.each do |chr|
            if chr.size > 1 
                chr.each do |n|
                    if n == "-"
                        n_chr.append(input)
                    end
                end
            else
                chr.each do |n|
                    if n == "-"
                        n_chr.append(input)
                    end
                end
            end
        end
        end 
        @x_chr = @x_chr - n_chr
        if n_chr.empty?
            n_chr = @x_chr
        end
        %>
        <div class="row">
          <div class="large-3 column">
            <h5>Chr. X</h5>
            <% if n_chr == @x_chr %>
              <% n_chr.each do |chromosomes| %>
                <% if checkLetality(chromosomes,@balancers,@lethal) == false %>
                  <div class="button small secondary hollow">
                    <%= chromosomeMath(chromosomes) %>
                    &#x2642;
                    <% if @x_chr.size == 1 %>
                      <%= radio_button_tag(:m_X, cleanChromosome(chromosomes), :checked => true) %>
                    <% else %>
                      <%= radio_button_tag(:m_X, cleanChromosome(chromosomes)) %>
                    <% end %>
                    &#x2640;
                    <% if @x_chr.size == 1 %>
                      <%= radio_button_tag(:f_X, cleanChromosome(chromosomes), :checked => true) %>
                    <% else %>
                      <%= radio_button_tag(:f_X, cleanChromosome(chromosomes)) %>
                    <% end %>
                  </div><br />
                <% end %>
              <% end %>
            <% else %>
              <% n_chr.each do |chromosomes| %>
                <% if checkLetality(chromosomes,@balancers,@lethal) == false %>
                  <div class="button small secondary hollow">
                    <%= chromosomeMath(chromosomes) %>
                    &#x2642;
                    <% if @x_chr.size == 1 %>
                      <%= radio_button_tag(:m_X, cleanChromosome(chromosomes), :checked => true) %>
                    <% else %>
                      <%= radio_button_tag(:m_X, cleanChromosome(chromosomes)) %>
                    <% end %>
                  </div><br />
                <% end %>
              <% end %>
              <% @x_chr.each do |chromosomes| %>
                <% if checkLetality(chromosomes,@balancers,@lethal) == false %>
                  <div class="button small secondary hollow">
                    <%= chromosomeMath(chromosomes) %>
                    &#x2640;
                    <% if @x_chr.size == 1 %>
                      <%= radio_button_tag(:f_X, cleanChromosome(chromosomes), :checked => true) %>
                    <% else %>
                      <%= radio_button_tag(:f_X, cleanChromosome(chromosomes)) %>
                    <% end %>
                  </div><br />
                <% end %>
              <% end %>
            <% end %>
          </div>
          <div class="large-3 column">
            <h5>Chr. II</h5>
            <% @II_chr.each do |chromosomes| %>
              <% if checkLetality(chromosomes,@balancers,@lethal) == false %>
                <div class="button small secondary hollow">
                  <%= chromosomeMath(chromosomes) %>
                  &#x2642;
                    <% if @II_chr.size == 1 %>
                    <%= radio_button_tag(:m_II, cleanChromosome(chromosomes), :checked => true) %>
                  <% else %>
                    <%= radio_button_tag(:m_II, cleanChromosome(chromosomes)) %>
                  <% end %>
                  &#x2640;
                    <% if @II_chr.size == 1 %>
                    <%= radio_button_tag(:f_II, cleanChromosome(chromosomes), :checked => true) %>
                  <% else %>
                    <%= radio_button_tag(:f_II, cleanChromosome(chromosomes)) %>
                  <% end %>
                </div><br />
              <% end %>
            <% end %>
          </div>
          <div class="large-3 column">
            <h5>Chr. III</h5>
            <% @III_chr.each do |chromosomes| %>
              <% if checkLetality(chromosomes,@balancers,@lethal) == false %>
                <div class="button small secondary hollow">
                  <%= chromosomeMath(chromosomes) %>
                  &#x2642;
                    <% if @III_chr.size == 1 %>
                    <%= radio_button_tag(:m_III, cleanChromosome(chromosomes), :checked => true) %>
                  <% else %>
                    <%= radio_button_tag(:m_III, cleanChromosome(chromosomes)) %>
                  <% end %>
                  &#x2640;
                    <% if @III_chr.size == 1 %>
                    <%= radio_button_tag(:f_III, cleanChromosome(chromosomes), :checked => true) %>
                  <% else %>
                    <%= radio_button_tag(:f_III, cleanChromosome(chromosomes)) %>
                  <% end %>
                </div><br />
              <% end %>
            <% end %>
          </div>
          <div class="large-3 column">
            <h5>Chr. IV</h5>
            <% @IV_chr.each do |chromosomes| %>
              <% if checkLetality(chromosomes,@balancers,@lethal) == false %>
                <div class="button small secondary hollow">
                  <%= chromosomeMath(chromosomes) %>
                  &#x2642;
                    <% if @IV_chr.size == 1 %>
                    <%= radio_button_tag(:m_IV, cleanChromosome(chromosomes), :checked => true) %>
                  <% else %>
                    <%= radio_button_tag(:m_IV, cleanChromosome(chromosomes)) %>
                  <% end %>
                  &#x2640;
                    <% if @IV_chr.size == 1 %>
                    <%= radio_button_tag(:f_IV, cleanChromosome(chromosomes), :checked => true) %>
                  <% else %>
                    <%= radio_button_tag(:f_IV, cleanChromosome(chromosomes)) %>
                  <% end %>
                </div><br />
              <% end %>
            <% end %>
          </div>
        </div>
      <% end end %>
      Select if you want to use a fly from the chromosome view:
      &#x2642;
          <%= f.radio_button(:male_id, "male_chr_s", :checked => true) %>
              | &#x2640;
          <%= f.radio_button(:female_id, "female_chr_s", :checked => true) %> <br />
      <%= f.submit 'Cross', class: 'button success' %>
    </div>
    <div class="large-4 column">
      <% 
if user_signed_in?
if g_user.id == current_user.id
    %>
      <h3>Next cross</h3>
      <div class="panel">
        <%= f.hidden_field(:balancers, :value => @balancer_string) %>
        <%= f.hidden_field(:lethal, :value => @lethal_string) %>
        <%= f.hidden_field(:parent, :value => @cross.id) %>
        <%= f.hidden_field(:link, :value => @random_string) %>
        <p>
          <div>
            <div class="callout secondary">
              <h5>Genotype</h5>
              &#x2642;
          <%= f.radio_button(:male_id, "new", label: false) %>
              | &#x2640;
          <%= f.radio_button(:female_id, "new", label: false) %>
              <h6>Separate sister chromosomes with a slash [/] and alleles on the same chromosome with a comma [,]</h6>
              <div class="row">
                <div class="large-6 columns">
                  <label>X chromosome
          <%= f.text_field :X, :value => "+/+" %>
                  </label>
                </div>
                <div class="large-6 columns">
                  <label>Chromosome 2
          <%= f.text_field :II, :value => "+/+" %>
                  </label>
                </div>
                <div class="large-6 columns">
                  <label>Chromosome 3
          <%= f.text_field :III, :value => "+/+" %>
                  </label>
                </div>
                <div class="large-6 columns">
                  <label>Chromosome 4
          <%= f.text_field :IV, :value => "+/+" %>
                  </label>
                </div>
              </div>
            </div>
          </div>
        </p>
        <h5>Lethal alleles</h5>
        <label>Alleles separated by semicolon (;)
          <%= f.text_field :lethal %>
        </label>
        <h5>Balancers</h5>
        <label>Balancers separated by semicolon (;)
          <%= f.text_field :balancers %>
        </label>
        <h5>Comments</h5>
        <label>Describe this cross
          <%= f.text_field :description %>
        </label>
        <h5>Date of cross</h5>
        <%= f.date_select(:crossdate, selected: Date.today) %>
      </div>
    <% end %>
  <% end 
end%>
</div>
</div>
</div>

app/views/crosses/index.html.erb
<div class="white-bg">
<nav aria-label="You are here:" role="navigation">
  <ul class="breadcrumbs">
    <li><a href="<%= request.base_url %>">Drosophila.me</a></li>
    <li>
      <span class="show-for-sr">Current: </span> Crosses
          </li>
  </ul>
</nav>
<h1>Listing Crosses</h1>
<a href="<%= new_cross_path %>" class="button small secondary">New Cross</a>
<%
lastmonth = ""
lastyear = ""
%>
<% @crosses.each do |cross| %>
  <%
if lastmonth != cross.crossdate.strftime("%B") or lastyear != lastyear = cross.crossdate.strftime("%Y")
%>
    <div class="panel">
      <h4><%= cross.crossdate.strftime("%B %Y")%></h4>
    </div>
    <%
end

lastmonth = cross.crossdate.strftime("%B")
lastyear = cross.crossdate.strftime("%Y")
%>
    <% @flym = Fly.find(cross.male_id) %>
    <% @flyf = Fly.find(cross.female_id) %>
    <a href="<%= short_path(cross.friendly_id) %>">
      <div class="callout">
        <h6>
          <% chromosomes = [@flym.chr1.split('/').to_set, @flym.chr2.split('/').to_set, @flym.chr3.split('/').to_set, @flym.chr4.split('/').to_set] %>
          \[
              <% semikolon = 0 %>
          <% chromosomes.each do |chr| %>
            <% if chr.size > 1 %>
              <% if semikolon != 0 %>;<% end %>
              <% chr %>
              \dfrac
                    <% chr.each do |n| %>
                {<%= n %>}
                    <% end %>
            <% else %>
              <% if semikolon != 0 %>;<% end %>
              <% chr.each do |n| %>
                <%= n %>
              <% end %>
            <% end %>
            <% semikolon = 1 %>
          <% end %>
          \qquad X \qquad
    <% chromosomes = [@flyf.chr1.split('/').to_set, @flyf.chr2.split('/').to_set, @flyf.chr3.split('/').to_set, @flyf.chr4.split('/').to_set] %>
          <% semikolon = 0 %>
          <% chromosomes.each do |chr| %>
            <% if chr.size > 1 %>
              <% if semikolon != 0 %>;<% end %>
              <% chr %>
              \dfrac
                    <% chr.each do |n| %>
                {<%= n %>}
                    <% end %>
            <% else %>
              <% if semikolon != 0 %>;<% end %>
              <% chr.each do |n| %>
                <%= n %>
              <% end %>
            <% end %>
            <% semikolon = 1 %>
          <% end %>
          \]
  </h6>
        <p><%= cross.description %></p>
        <p><%= cross.crossdate.strftime("Crossed on %B %d, %Y") %></p>
      </div>
    </a>
  <% end %>
</div>